"""Detection signals, score combination, and transparency-label generation.

Two independent signals:
  - Signal 1 (semantic):   Groq LLM classifier  -> llm_ai_probability  [0,1]
  - Signal 2 (structural): stylometric heuristics -> stylometric_score [0,1]
Both express "probability the text is AI-generated", where 1.0 == definitely AI.
"""

import json
import os
import re
import statistics

from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Thresholds & weights (single source of truth — must match planning.md §2/§3)
# ---------------------------------------------------------------------------
AI_THRESHOLD = 0.65        # ai_score >= this  -> likely_ai
HUMAN_THRESHOLD = 0.35     # ai_score <= this  -> likely_human
LLM_WEIGHT = 0.65          # normal weighting
STYLO_WEIGHT = 0.35
LLM_WEIGHT_DEGRADED = 0.20  # used when the LLM signal fell back to neutral
STYLO_WEIGHT_DEGRADED = 0.80
MIN_TEXT_CHARS = 40        # below this we treat the input as too short to trust

LLM_MODEL = "llama-3.3-70b-versatile"


# ===========================================================================
# Signal 1 — LLM classifier (Groq)
# ===========================================================================
def llm_signal(text: str) -> dict:
    """Ask Groq to judge AI-vs-human. Returns
    {ai_probability: float[0,1], reasoning: str, degraded: bool}.
    On any failure, returns a neutral 0.5 flagged degraded=True so a network
    error cannot masquerade as a real verdict."""
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {"ai_probability": 0.5, "reasoning": "No GROQ_API_KEY set.",
                "degraded": True}

    prompt = (
        "You are a forensic text-attribution classifier. Assess whether the "
        "TEXT below was written by a human or generated by an AI language model. "
        "Consider tone, specificity, lived detail, and the subtle over-smoothness "
        "typical of AI text. Respond ONLY with strict JSON of the form "
        '{\"ai_probability\": <float 0..1>, \"reasoning\": \"<one sentence>\"} '
        "where 1.0 means definitely AI-generated and 0.0 means definitely "
        "human-written.\n\nTEXT:\n\"\"\"\n" + text + "\n\"\"\""
    )
    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=200,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        prob = float(data.get("ai_probability", 0.5))
        prob = max(0.0, min(1.0, prob))
        return {
            "ai_probability": prob,
            "reasoning": str(data.get("reasoning", "")).strip(),
            "degraded": False,
        }
    except Exception as exc:  # network, parse, auth, rate-limit, etc.
        return {"ai_probability": 0.5,
                "reasoning": f"LLM signal unavailable ({type(exc).__name__}).",
                "degraded": True}


# ===========================================================================
# Signal 2 — Stylometric heuristics (pure Python)
# ===========================================================================
AI_CLICHES = [
    "furthermore", "moreover", "in conclusion", "it is important to note",
    "it is worth noting", "delve", "tapestry", "navigate the complexities",
    "in today's", "ever-evolving", "paradigm shift", "underscore",
    "multifaceted", "it is essential", "plays a crucial role", "in summary",
    "a testament to", "when it comes to", "the realm of", "foster",
]
INFORMAL_MARKERS = [
    "lol", "honestly", "tbh", "ok so", "okay so", "kinda", "gonna", "wanna",
    "yeah", "idk", "like seriously", "ngl", "??", "!!", "...",
]
CONTRACTION_RE = re.compile(r"\b\w+'(s|t|re|ve|ll|d|m)\b", re.IGNORECASE)


def _split_sentences(text: str):
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p for p in parts if p.strip()]


def _clamp01(x):
    return max(0.0, min(1.0, x))


def stylometric_signal(text: str) -> dict:
    """Return {stylometric_score: float[0,1], metrics: {...}}.
    Higher score == more AI-like. Combines four weighted sub-metrics."""
    words = re.findall(r"[A-Za-z']+", text.lower())
    n_words = len(words)
    sentences = _split_sentences(text)
    lengths = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences]
    lengths = [l for l in lengths if l > 0]

    # --- (a) Burstiness: coefficient of variation of sentence length ---
    if len(lengths) >= 2 and statistics.mean(lengths) > 0:
        cv = statistics.pstdev(lengths) / statistics.mean(lengths)
    else:
        cv = 0.5  # too few sentences to judge -> neutral-ish
    # Low CV -> AI. Map CV: <=0.2 -> 1.0 (AI), >=0.7 -> 0.0 (human).
    burstiness_ai = _clamp01((0.7 - cv) / (0.7 - 0.2))

    # --- (b) AI-cliche / transition density (per 100 words) ---
    low = text.lower()
    cliche_hits = sum(low.count(p) for p in AI_CLICHES)
    cliche_rate = (cliche_hits / n_words * 100) if n_words else 0
    # 0 hits -> 0.0 ; ~3 per 100 words -> ~1.0
    cliche_ai = _clamp01(cliche_rate / 3.0)

    # --- (c) Informality markers -> pushes toward human ---
    informal_hits = sum(low.count(m) for m in INFORMAL_MARKERS)
    contractions = len(CONTRACTION_RE.findall(text))
    lowercase_starts = sum(
        1 for s in sentences if s[:1].isalpha() and s[:1].islower()
    )
    informal_signal = informal_hits + contractions + lowercase_starts
    informal_rate = (informal_signal / n_words * 100) if n_words else 0
    # More informality -> lower AI-likeness. ~2 per 100 words -> fully human (0.0).
    informal_ai = _clamp01(1.0 - informal_rate / 2.0)

    # --- (d) Lexical diversity: type-token ratio ---
    ttr = (len(set(words)) / n_words) if n_words else 0.5
    # Very low TTR (repetitive) nudges AI-like; high TTR nudges human.
    # Map TTR: >=0.75 -> 0.0 (human), <=0.35 -> 1.0 (AI).
    ttr_ai = _clamp01((0.75 - ttr) / (0.75 - 0.35))

    score = (
        0.40 * burstiness_ai
        + 0.30 * cliche_ai
        + 0.20 * informal_ai
        + 0.10 * ttr_ai
    )

    return {
        "stylometric_score": round(_clamp01(score), 4),
        "metrics": {
            "n_words": n_words,
            "n_sentences": len(lengths),
            "sentence_length_cv": round(cv, 3),
            "burstiness_ai": round(burstiness_ai, 3),
            "cliche_rate_per_100w": round(cliche_rate, 3),
            "cliche_ai": round(cliche_ai, 3),
            "informal_rate_per_100w": round(informal_rate, 3),
            "informal_ai": round(informal_ai, 3),
            "type_token_ratio": round(ttr, 3),
            "ttr_ai": round(ttr_ai, 3),
        },
    }


# ===========================================================================
# Combination + classification
# ===========================================================================
def combine_and_classify(text: str) -> dict:
    """Run both signals, blend into ai_score, derive attribution + confidence."""
    llm = llm_signal(text)
    stylo = stylometric_signal(text)

    llm_score = llm["ai_probability"]
    stylo_score = stylo["stylometric_score"]

    if llm["degraded"]:
        w_llm, w_stylo = LLM_WEIGHT_DEGRADED, STYLO_WEIGHT_DEGRADED
    else:
        w_llm, w_stylo = LLM_WEIGHT, STYLO_WEIGHT

    ai_score = w_llm * llm_score + w_stylo * stylo_score

    # Short inputs are statistically unreliable -> pull toward uncertain (0.5).
    short = len(text.strip()) < MIN_TEXT_CHARS
    if short:
        ai_score = 0.5 + (ai_score - 0.5) * 0.5

    ai_score = round(_clamp01(ai_score), 4)

    if ai_score >= AI_THRESHOLD:
        attribution = "likely_ai"
    elif ai_score <= HUMAN_THRESHOLD:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    confidence = round(max(ai_score, 1.0 - ai_score), 4)

    return {
        "attribution": attribution,
        "confidence": confidence,
        "ai_score": ai_score,
        "llm_score": round(llm_score, 4),
        "stylometric_score": round(stylo_score, 4),
        "llm_reasoning": llm["reasoning"],
        "llm_degraded": llm["degraded"],
        "stylometric_metrics": stylo["metrics"],
        "short_input": short,
        "weights": {"llm": w_llm, "stylometric": w_stylo},
    }


# ===========================================================================
# Transparency label
# ===========================================================================
def generate_label(attribution: str, confidence: float) -> dict:
    """Map attribution + confidence to one of three reader-facing variants."""
    pct = round(confidence * 100)
    if attribution == "likely_ai":
        return {
            "variant": "high_confidence_ai",
            "headline": "🤖 Likely AI-Generated",
            "confidence_pct": pct,
            "text": (
                f"🤖 Likely AI-Generated — Our analysis suggests this content was "
                f"most likely produced by an AI system (confidence: {pct}%). Both "
                f"our language-model check and our writing-style check pointed "
                f"toward automated generation. This is an automated estimate, not "
                f"a certainty. If you wrote this yourself, you can appeal."
            ),
        }
    if attribution == "likely_human":
        return {
            "variant": "high_confidence_human",
            "headline": "✍️ Likely Human-Written",
            "confidence_pct": pct,
            "text": (
                f"✍️ Likely Human-Written — Our analysis suggests this content was "
                f"most likely written by a person (confidence: {pct}%). The writing "
                f"showed the natural variation and voice typical of human authors. "
                f"This is an automated estimate and may be wrong."
            ),
        }
    return {
        "variant": "uncertain",
        "headline": "❓ Attribution Uncertain",
        "confidence_pct": pct,
        "text": (
            f"❓ Attribution Uncertain — We could not confidently determine whether "
            f"this content was written by a person or generated by AI (confidence: "
            f"{pct}%). Our two checks were borderline or disagreed with each other. "
            f"Please treat the origin of this content as unknown."
        ),
    }
